"""add_language_to_interview_session

Revision ID: 42919a12391a
Revises: 9f43fddb47e8
Create Date: 2026-06-08 10:46:41.436779

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import pgvector


# revision identifiers, used by Alembic.
revision: str = '42919a12391a'
down_revision: Union[str, Sequence[str], None] = '9f43fddb47e8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('interview_sessions', sa.Column('language', sa.String(length=50), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('interview_sessions', 'language')
    # ### end Alembic commands ###
