"""add_cascade_delete_to_user_relations

Revision ID: 58f2c69a56ae
Revises: 42919a12391a
Create Date: 2026-06-09 00:59:52.983425

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import pgvector


# revision identifiers, used by Alembic.
revision: str = '58f2c69a56ae'
down_revision: Union[str, Sequence[str], None] = '42919a12391a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('cv_analyses_cv_id_fkey'), 'cv_analyses', type_='foreignkey')
    op.drop_constraint(op.f('cv_analyses_user_id_fkey'), 'cv_analyses', type_='foreignkey')
    op.create_foreign_key(None, 'cv_analyses', 'users', ['user_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(None, 'cv_analyses', 'cv_uploads', ['cv_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint(op.f('cv_uploads_user_id_fkey'), 'cv_uploads', type_='foreignkey')
    op.create_foreign_key(None, 'cv_uploads', 'users', ['user_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint(op.f('interview_answers_session_id_fkey'), 'interview_answers', type_='foreignkey')
    op.create_foreign_key(None, 'interview_answers', 'interview_sessions', ['session_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint(op.f('interview_sessions_user_id_fkey'), 'interview_sessions', type_='foreignkey')
    op.create_foreign_key(None, 'interview_sessions', 'users', ['user_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'interview_sessions', type_='foreignkey')
    op.create_foreign_key(op.f('interview_sessions_user_id_fkey'), 'interview_sessions', 'users', ['user_id'], ['id'])
    op.drop_constraint(None, 'interview_answers', type_='foreignkey')
    op.create_foreign_key(op.f('interview_answers_session_id_fkey'), 'interview_answers', 'interview_sessions', ['session_id'], ['id'])
    op.drop_constraint(None, 'cv_uploads', type_='foreignkey')
    op.create_foreign_key(op.f('cv_uploads_user_id_fkey'), 'cv_uploads', 'users', ['user_id'], ['id'])
    op.drop_constraint(None, 'cv_analyses', type_='foreignkey')
    op.drop_constraint(None, 'cv_analyses', type_='foreignkey')
    op.create_foreign_key(op.f('cv_analyses_user_id_fkey'), 'cv_analyses', 'users', ['user_id'], ['id'])
    op.create_foreign_key(op.f('cv_analyses_cv_id_fkey'), 'cv_analyses', 'cv_uploads', ['cv_id'], ['id'])
    # ### end Alembic commands ###
