"""add_interview_context

Revision ID: 9f43fddb47e8
Revises: 4b566f945ec7
Create Date: 2026-06-08 02:06:13.125104

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import pgvector


# revision identifiers, used by Alembic.
revision: str = '9f43fddb47e8'
down_revision: Union[str, Sequence[str], None] = '4b566f945ec7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('interview_sessions', sa.Column('cv_id', sa.Integer(), nullable=True))
    op.add_column('interview_sessions', sa.Column('jd_id', sa.Integer(), nullable=True))
    op.add_column('interview_sessions', sa.Column('custom_jd', sa.Text(), nullable=True))
    op.create_foreign_key(None, 'interview_sessions', 'cv_uploads', ['cv_id'], ['id'], ondelete='SET NULL')
    op.create_foreign_key(None, 'interview_sessions', 'job_descriptions', ['jd_id'], ['id'], ondelete='SET NULL')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'interview_sessions', type_='foreignkey')
    op.drop_constraint(None, 'interview_sessions', type_='foreignkey')
    op.drop_column('interview_sessions', 'custom_jd')
    op.drop_column('interview_sessions', 'jd_id')
    op.drop_column('interview_sessions', 'cv_id')
    # ### end Alembic commands ###
