"""add_api_key_usages_table

Revision ID: a5f82bb52541
Revises: 58f2c69a56ae
Create Date: 2026-06-13 19:28:00.000000

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a5f82bb52541'
down_revision: Union[str, Sequence[str], None] = '58f2c69a56ae'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        'api_key_usages',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('provider', sa.String(length=50), nullable=False),
        sa.Column('key_hash', sa.String(length=64), nullable=False),
        sa.Column('request_count', sa.Integer(), nullable=False, server_default='0'),
        sa.Column('error_count', sa.Integer(), nullable=False, server_default='0'),
        sa.Column('rate_limit_count', sa.Integer(), nullable=False, server_default='0'),
        sa.Column('last_used_at', sa.DateTime(timezone=True), nullable=True),
        sa.Column('created_at', sa.DateTime(timezone=True), nullable=False, server_default=sa.text('now()')),
        sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False, server_default=sa.text('now()')),
        sa.PrimaryKeyConstraint('id'),
        sa.UniqueConstraint('key_hash')
    )
    op.create_index(op.f('ix_api_key_usages_id'), 'api_key_usages', ['id'], unique=False)
    op.create_index(op.f('ix_api_key_usages_provider'), 'api_key_usages', ['provider'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_api_key_usages_provider'), table_name='api_key_usages')
    op.drop_index(op.f('ix_api_key_usages_id'), table_name='api_key_usages')
    op.drop_table('api_key_usages')
    # ### end Alembic commands ###
